import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 30,
    backgroundColor: '#F0F3F4', // Açık ve nötr bir arka plan
  },
  backButton: {
    position: 'absolute',
    top: 15,
    left: 10,
    zIndex: 10,
    padding: 10,
  },
  backButtonText: {
    fontSize: 32,
    color: '#4CAF50', // Yeşilin sakin bir tonu
    fontWeight: 'bold',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 20,
    textAlign: 'center',
    color: '#2C3E50',
  },
  input: {
    backgroundColor: '#FFFFFF',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#CED6E0',
    fontSize: 16,
    color: '#34495E',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  filterBtn: {
    backgroundColor: '#E8F0FE',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#A3C4F3',
    shadowColor: '#A3C4F3',
    shadowOpacity: 0.25,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  summaryBox: {
    backgroundColor: '#DFF0D8',
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#B2D8B2',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  typeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 15,
  },
  typeButton: {
    paddingVertical: 14,
    paddingHorizontal: 25,
    marginHorizontal: 10,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#A3C4F3',
    backgroundColor: '#F7F9FC',
  },
  selectedType: {
    backgroundColor: '#4CAF50',
    borderColor: '#388E3C',
  },
  typeText: {
    color: '#34495E',
    fontWeight: '600',
    fontSize: 16,
  },
  datePickerButton: {
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CED6E0',
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  datePickerText: {
    fontSize: 16,
    color: '#34495E',
  },
  recordCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 18,
    borderRadius: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  paidRecordCard: {
    backgroundColor: '#D1E7DD',
  },
  recordName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2C3E50',
    marginBottom: 5,
  },
});
